### ISSUE TITLE
sudo-shutdown-mobile.txt 权限问题可以用polkit解决

### ISSUE THREAD

**Issue by linfangrong** [GHolk/Gholk.github.io#1]
sudo-shutdown-mobile.txt 中可以不需要加入sudo权限，通过linux自带polkit去控制权限问题。

比如所有用户都制定关机权限，而且不需要验证信息。

cat /etc/polkit-1/localauthority/50-local.d/enable-power-off.pkla
```
[Enable poweroff]
Identity=unix-user:*
Action=org.freedesktop.login1.power-off;org.freedesktop.login1.power-off-multiple-sessions
ResultAny=yes
ResultInactive=yes
ResultActive=yes
```

**Comment by GHolk** [comment]
謝啦，
我一直找不到怎麼設關機權限，
不過你為什麼用issue 回XD
